batch_size: 100
workers: 0
nepoch: 100
model_name: houv
#load_model: ./log/houv/network.pth
load_model: null
start_epoch: 0
work_dir: log/
flag: debug
loss: cd
manual_seed: 2021

step_interval_to_print: 30
step_interval_to_plot: 250
epoch_interval_to_save: 10
epoch_interval_to_val: 1

num_points: 2048
descriptor_size: 512
max_angle: 180
max_trans: 0.5
category: null
benchmark: mvp
num_rot_levels: 2
num_corr_levels: 2
kernel: 32

lr: 0.01
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

# test
save_vis: False
eval_emd: False

# separate the test dataset, calculated on the multi GPUs.
l: 0
r: 4
combine: False 