batch_size: 10
workers: 0
nepoch: 100
model_name: vrcnet
load_model: ./log/vrcnet/network.pth
#load_model: null
start_epoch: 0
work_dir: log/
flag: debug
loss: cd
manual_seed: 2021

step_interval_to_print: 30
step_interval_to_plot: 250
epoch_interval_to_save: 10
epoch_interval_to_val: 1

use_rri: False
rri_size: 5
num_clusters: 16
num_points: 2048
use_tnet: False
use_fpfh: False
use_ppf: False
descriptor_size: 512
max_angle: 180
max_trans: 0.5
category: null
benchmark: mvp
num_rot_levels: 2
num_corr_levels: 2


lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

# test
save_vis: False
eval_emd: False

l: 0
r: 4
combine: False