batch_size: 16
every_batch_size: 16
workers: 2
nepoch: 100
model_name: vrcnet_knn
#load_model: ./log/vrcnet_knn_cd_debug_2021-07-27T14:00:50/best_cd_t_network.pth
load_model: null
start_epoch: 0
work_dir: log/
flag: debug
loss: cd
manual_seed: null
use_mean_feature: False
step_interval_to_print: 500
epoch_interval_to_save: 1
epoch_interval_to_val: 1
varying_constant: 0.01, 0.1, 0.5, 1
varying_constant_epochs: 5, 15, 30

lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

layers: 1, 1, 1, 1
knn_list: "16"
pk: 10

points_label: True
num_coarse: 1024
num_fine: 3072
num_native: 2048
feature_size: 2048

# test
save_vis: False
eval_emd: False